[package]
name = "palettevec"
version = "0.1.0"
edition = "2021"
authors = ["alexdesander <alexdesander@tuta.io>"]
description = "A palette compressed vector library for potentially insane runtime compression ratios."
keywords = ["gamedev", "encoding", "memory", "vector", "compression"]
categories = ["compression", "data-structures"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexdesander/palettevec"

[dependencies]

[dev-dependencies]
rand = "0.8.5"
